### ISSUE TITLE
could not find pdf 

### ISSUE THREAD

**Issue by vipin733** [spatie/pdf-to-text#4]
```
// $return = Storage::disk('local')->put('file.pdf', $request->filename);

	$filename = $request->file('filename')->store('');
	// $path = storage_path() . '\' . $name;
	// $file = Storage::get('app/'.$name);
     $return = \Spatie\PdfToText\Pdf::getText('some/16fJLA9iGiOfRCcEot43S9LtSRAYE6mq4ZzeBwdM.pdf', '/mingw64/bin/pdftotext');

     return $return;
```
I'm using laravel.5.5 and its file available in my public folder evry time when i hit submit I'm getting error 

```
[2017-09-26 18:08:38] local.ERROR: could not find pdf /some/16fJLA9iGiOfRCcEot43S9LtSRAYE6mq4ZzeBwdM.pdf {"exception":"[object] (Spatie\\PdfToText\\Exceptions\\PdfNotFound(code: 0): could not find pdf /some/16fJLA9iGiOfRCcEot43S9LtSRAYE6mq4ZzeBwdM.pdf at E:\\laragon\\www\\precilyl\\vendor\\spatie\\pdf-to-text\\src\\Pdf.php:23)
[stacktrace]
#0 E:\\laragon\\www\\precilyl\\vendor\\spatie\\pdf-to-text\\src\\Pdf.php(46): Spatie\\PdfToText\\Pdf->setPdf('/some/16fJLA9iG...')
#1 E:\\laragon\\www\\precilyl\
outes\\api.php(28): Spatie\\PdfToText\\Pdf::getText('/some/16fJLA9iG...', '/mingw64/bin/pd...')
#2 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(190): Illuminate\\Routing\\Router->{closure}(Object(Illuminate\\Http\\Request))
#3 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(164): Illuminate\\Routing\\Route->runCallable()
#4 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(610): Illuminate\\Routing\\Route->run()
#5 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\
````

**Comment by freekmurze** [comment]
This error is not caused by this package. Make sure that the pdf exists at the path you pass to `getText`.

First guess when looking at your code is that you should append the public path:

```php
$path = public_path('some/16fJLA9iGiOfRCcEot43S9LtSRAYE6mq4ZzeBwdM.pdf');

\Spatie\PdfToText\Pdf::getText($path, '/mingw64/bin/pdftotext');
```

**Comment by vipin733** [comment]
```
Error Output:
================
The system cannot find the path specified.
 at E:\\laragon\\www\\precilyl\\vendor\\spatie\\pdf-to-text\\src\\Pdf.php:37)
[stacktrace]
#0 E:\\laragon\\www\\precilyl\\vendor\\spatie\\pdf-to-text\\src\\Pdf.php(47): Spatie\\PdfToText\\Pdf->text()
#1 E:\\laragon\\www\\precilyl\
outes\\api.php(29): Spatie\\PdfToText\\Pdf::getText('E:\\\\laragon\\\\www\\\\...', '/mingw64/bin/pd...')
#2 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(190): Illuminate\\Routing\\Router->{closure}(Object(Illuminate\\Http\\Request))
#3 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(164): Illuminate\\Routing\\Route->runCallable()
#4 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(610): Illuminate\\Routing\\Route->run()
#5 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#7 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#11 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(571): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#15 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(549): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 E:\\laragon\\www\\precilyl\\vendor\\barryvdh\\laravel-cors\\src\\HandleCors.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 E:\\laragon\\www\\precilyl\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 E:\\laragon\\www\\precilyl\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#39 E:\\laragon\\www\\precilyl\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#40 {main}
"} 
[2017-09-27 05:00:56] local.ERROR: The command "\mingw64\bin\pdftotext 'E:\laragon\www\precilyl\public\some/16fJLA9iGiOfRCcEot43S9LtSRAYE6mq4ZzeBwdM.pdf' -" failed.

Exit Code: 1(General error)

Working directory: E:\laragon\www\precilyl\public```
when I run "which pdftotext" it give me path "\mingw64\bin\pdftotext "  but why it not found path

**Comment by apzeero** [comment]
If you're using Laragon on Windows, check your git directory for mingw64. Custom path to pdftotext should look something like: `drive:/laragon/bin/git/mingw64/bin/pdftotext`.

**Comment by hmimeee** [comment]
> If you're using Laragon on Windows, check your git directory for mingw64. Custom path to pdftotext should look something like: `drive:/laragon/bin/git/mingw64/bin/pdftotext`.

Thanks @apzeero for this valuable answer. Problem solved!!! 🥳
